# Generated by Django 3.1.14 on 2023-03-06 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Lot',
            new_name='Lon',
        ),
    ]
