# Generated by Django 3.1.14 on 2023-03-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20230308_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolution_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_evolution_to', to='pokemon_entities.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolution_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_evolution_from', to='pokemon_entities.pokemon'),
        ),
    ]
